# Enable compile command to ease indexing with e.g. clangd
set(CMAKE_EXPORT_COMPILE_COMMANDS TRUE)

# Compiler options
target_compile_options(${BUILD_UNIT_0_NAME} PRIVATE
    $<$<COMPILE_LANGUAGE:C>: ${CUBE_CMAKE_C_FLAGS}>
    $<$<COMPILE_LANGUAGE:CXX>: ${CUBE_CMAKE_CXX_FLAGS}>
    $<$<COMPILE_LANGUAGE:ASM>: ${CUBE_CMAKE_ASM_FLAGS}>
)

# Linker options
target_link_options(${BUILD_UNIT_0_NAME} PRIVATE ${CUBE_CMAKE_EXE_LINKER_FLAGS})

# Add sources to executable/library
target_sources(${BUILD_UNIT_0_NAME} PRIVATE
    "Core/Src/app_debug.c"
    "Core/Src/app_entry.c"
    "Core/Src/hw_timerserver.c"
    "Core/Src/hw_uart.c"
    "Core/Src/main.c"
    "Core/Src/stm32_lpm_if.c"
    "Core/Src/stm32wbxx_hal_msp.c"
    "Core/Src/stm32wbxx_it.c"
    "Core/Src/syscalls.c"
    "Core/Src/sysmem.c"
    "Core/Src/system_stm32wbxx.c"
    "Core/Startup/startup_stm32wb5mmghx.s"
    "Drivers/BSP/stm32_adafruit_sd.c"
    "Drivers/BSP/stm32wbxx_nucleo.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_adc.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_adc_ex.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_cortex.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_dma.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_dma_ex.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_exti.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_flash.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_flash_ex.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_gpio.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_hsem.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_i2c.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_i2c_ex.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_ipcc.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_iwdg.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pcd.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pcd_ex.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pwr.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pwr_ex.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rcc.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rcc_ex.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rng.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rtc.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rtc_ex.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_sai.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_sai_ex.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_spi.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_spi_ex.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_tim.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_tim_ex.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_uart.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_uart_ex.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_ll_adc.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_ll_rcc.c"
    "Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_ll_usb.c"
    "FATFS/App/app_fatfs.c"
    "FATFS/Target/user_diskio.c"
    "FlySight/active_control.c"
    "FlySight/active_mode.c"
    "FlySight/activelook.c"
    "FlySight/activelook_draw.c"
    "FlySight/activelook_mode0.c"
    "FlySight/activelook_mode1.c"
    "FlySight/audio.c"
    "FlySight/audio_control.c"
    "FlySight/baro.c"
    "FlySight/button.c"
    "FlySight/charge.c"
    "FlySight/common.c"
    "FlySight/config.c"
    "FlySight/config_mode.c"
    "FlySight/crs.c"
    "FlySight/device_state.c"
    "FlySight/flight_params.c"
    "FlySight/gnss.c"
    "FlySight/gnss_mock.c"
    "FlySight/gnss_ble.c"
    "FlySight/hts221.c"
    "FlySight/hum.c"
    "FlySight/imu.c"
    "FlySight/led.c"
    "FlySight/log.c"
    "FlySight/mag.c"
    "FlySight/md5.c"
    "FlySight/mode.c"
    "FlySight/nav.c"
    "FlySight/pairing_mode.c"
    "FlySight/resource_manager.c"
    "FlySight/rtc_util.c"
    "FlySight/scratch_buffer.c"
    "FlySight/sensor.c"
    "FlySight/sensor_data.c"
    "FlySight/sensor_time.c"
    "FlySight/sht4x.c"
    "FlySight/start_control.c"
    "FlySight/start_mode.c"
    "FlySight/state.c"
    "FlySight/time.c"
    "FlySight/usb_control.c"
    "FlySight/usb_mode.c"
    "FlySight/usb_storage_cache.c"
    "FlySight/vbat.c"
    "FlySight/vbus.c"
    "Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc.c"
    "Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_bot.c"
    "Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_data.c"
    "Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_scsi.c"
    "Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c"
    "Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c"
    "Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c"
    "Middlewares/ST/STM32_WPAN/ble/core/auto/ble_events.c"
    "Middlewares/ST/STM32_WPAN/ble/core/auto/ble_gap_aci.c"
    "Middlewares/ST/STM32_WPAN/ble/core/auto/ble_gatt_aci.c"
    "Middlewares/ST/STM32_WPAN/ble/core/auto/ble_hal_aci.c"
    "Middlewares/ST/STM32_WPAN/ble/core/auto/ble_hci_le.c"
    "Middlewares/ST/STM32_WPAN/ble/core/auto/ble_l2cap_aci.c"
    "Middlewares/ST/STM32_WPAN/ble/core/template/osal.c"
    "Middlewares/ST/STM32_WPAN/ble/svc/Src/svc_ctl.c"
    "Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci/shci.c"
    "Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl/hci_tl.c"
    "Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl/hci_tl_if.c"
    "Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl/shci_tl.c"
    "Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl/shci_tl_if.c"
    "Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl/tl_mbox.c"
    "Middlewares/ST/STM32_WPAN/utilities/dbg_trace.c"
    "Middlewares/ST/STM32_WPAN/utilities/otp.c"
    "Middlewares/ST/STM32_WPAN/utilities/stm_list.c"
    "Middlewares/ST/STM32_WPAN/utilities/stm_queue.c"
    "Middlewares/Third_Party/FatFs/src/diskio.c"
    "Middlewares/Third_Party/FatFs/src/ff.c"
    "Middlewares/Third_Party/FatFs/src/ff_gen_drv.c"
    "Middlewares/Third_Party/FatFs/src/option/syscall.c"
    "STM32_WPAN/App/activelook_client.c"
    "STM32_WPAN/App/app_ble.c"
    "STM32_WPAN/App/ble_tx_queue.c"
    "STM32_WPAN/App/custom_app.c"
    "STM32_WPAN/App/custom_stm.c"
    "STM32_WPAN/Target/hw_ipcc.c"
    "USB_Device/App/usb_device.c"
    "USB_Device/App/usbd_desc.c"
    "USB_Device/App/usbd_storage_if.c"
    "USB_Device/Target/usbd_conf.c"
    "Utilities/lpm/tiny_lpm/stm32_lpm.c"
    "Utilities/sequencer/stm32_seq.c"
)

target_include_directories(${BUILD_UNIT_0_NAME} PRIVATE
    "Core/Inc"
    "Drivers/STM32WBxx_HAL_Driver/Inc"
    "Drivers/STM32WBxx_HAL_Driver/Inc/Legacy"
    "Drivers/CMSIS/Device/ST/STM32WBxx/Include"
    "Drivers/CMSIS/Include"
    "STM32_WPAN/App"
    "Utilities/lpm/tiny_lpm"
    "Middlewares/ST/STM32_WPAN"
    "Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread"
    "Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl"
    "Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci"
    "Middlewares/ST/STM32_WPAN/utilities"
    "Middlewares/ST/STM32_WPAN/ble/core"
    "Middlewares/ST/STM32_WPAN/ble/core/auto"
    "Middlewares/ST/STM32_WPAN/ble/core/template"
    "Middlewares/ST/STM32_WPAN/ble/svc/Inc"
    "Middlewares/ST/STM32_WPAN/ble/svc/Src"
    "Utilities/sequencer"
    "Middlewares/ST/STM32_WPAN/ble"
    "USB_Device/App"
    "USB_Device/Target"
    "Middlewares/ST/STM32_USB_Device_Library/Core/Inc"
    "FlySight"
    "FATFS/Target"
    "FATFS/App"
    "Middlewares/Third_Party/FatFs/src"
    "Drivers/BSP"
    "Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc"
)

configure_file("${CMAKE_SOURCE_DIR}/STM32WB5MMGHX_FLASH.ld" "${CMAKE_BINARY_DIR}" COPYONLY)

set_target_properties(${BUILD_UNIT_0_NAME} PROPERTIES LINK_DEPENDS "STM32WB5MMGHX_FLASH.ld")

